version: '3.7'

services:
  web: 
    build: ./WebApp
    container_name: web
    restart: always
    volumes:
      - ./WebApp:/app
    environment: 
      FLASK_ENV: development
    ports:
      - "8080:8080"
    networks:
      - local
    depends_on:
      - api
    expose:
      - 8080
  
  api:
    build: "./API"
    container_name: api
    restart: always
    volumes:
      - ./API:/app
    environment: 
      FLASK_ENV: development
    ports:
      - "7070:7070"
    networks:
      - local
    expose:
      - 7070

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    environment:
      FLASK_ENV: development
    ports:
      - "80:80"
      - "70:70"
    networks:
      - local
  
networks:
  local:
    driver: bridge
    
      